Response status changes
pangeacyber/python-pangea pull request #78
Opened 2022-09-06 21:52 UTC by mcombspangea

This PR will

- Add pangea API exceptions
- Raise those exceptions if requests are not successful

2022-09-07 13:50 UTC, pangea-andrest requested changes

2022-09-07 13:50 UTC, pangea-andrest commented on pangea/exceptions.py
> +    """Audit service specific exceptions"""
"Embargo" services...

2022-09-07 13:50 UTC, pangea-andrest commented on pangea/response.py
> +        status (str): Pangea status code
Maybe sounds better to say "status message"?

2022-09-07 13:50 UTC, pangea-andrest commented on pangea/response.py
> +        data = status = requests_response.json()
Is it right to init status here and overwrite in next line?

2022-09-07 13:50 UTC, pangea-andrest commented on pangea/services/audit.py
>                  raise Exception(f"Error: Event hash failed.")
Should we update this exceptions to AuditException?

2022-09-07 13:50 UTC, pangea-andrest commented on pangea/services/audit.py
>                  raise Exception(f"Error: Membership proof failed.")
Also here and all remaining

2022-09-07 13:50 UTC, pangea-andrest commented on tests/integration/test_redact.py
> +        with self.assertRaises(exceptions.ValidationException):
Could you add a little comment about what are you testing and why it should raise an exception or not

2022-09-07 13:52 UTC, pangea-andrest commented
Also it would be great to have at least one test per service raising exception. Could you add them?

2022-09-07 17:17 UTC, mcombspangea commented on pangea/response.py
> +        data = status = requests_response.json()
typo.

2022-09-07 17:38 UTC, mcombspangea commented on tests/integration/test_redact.py
> +        with self.assertRaises(exceptions.ValidationException):
This is on line 32

2022-09-07 17:44 UTC, pangea-andrest commented on pangea/exceptions.py
> +    """Audit service specific exceptions"""
@mcombspangea This one remains, on the comment it says "Audit Service" and it should be "Embargo Service"

2022-09-08 20:22 UTC, pangea-andrest approved these changes

2022-09-08 20:28 UTC, merged